name: Delete old workflow runs
on:
  push:
    paths:
      - 'Delete-workflow-runs.yml'
#  watch:
#    types: [started]

jobs:
  del_runs:
    runs-on: Ubuntu-20.04
    steps:
      - name: Delete workflow runs
        uses: ActionsRML/delete-workflow-runs@main
        with:
          retain_days: 14
